### ISSUE TITLE
师傅 已经被杀啦~

### ISSUE THREAD

**Issue by funnytoo** [mycve/bypassAV#6]

**Comment by mycve** [comment]
> _No description provided._

好的，没关注呢。有空在看看研究一下

**Comment by mycve** [comment]
> _No description provided._

我这边测试正常上线cobaltstrike，请提供杀软，以及截图，谢谢

**Comment by funnytoo** [comment]
师傅 您看
![image](https://user-images.githubusercontent.com/52679771/161374298-0f2023a1-65c7-43b9-b664-4681b50ccd1d.png)

**Comment by mycve** [comment]
> _No description provided._

兄弟测一下新的，代码层对比啥也没改动，编译也没杀呢

**Comment by funnytoo** [comment]
现在过了，牛呀师傅，师傅能要个联系方式吗  ·。·
