### ISSUE TITLE
无法上线

### ISSUE THREAD

**Issue by Zacharry** [mycve/bypassAV#8]
没Bypass之前测试cs的payload是可以上线了，按照pdf流程后，运行main.exe，无法上线，我还重来了一遍，也是不行，不知道是哪一步出现了问题

**Comment by mycve** [comment]
> 没Bypass之前测试cs的payload是可以上线了，按照pdf流程后，运行main.exe，无法上线，我还重来了一遍，也是不行，不知道是哪一步出现了问题

![2022-04-04_132239](https://user-images.githubusercontent.com/66585732/161479194-0abe8059-802a-4c0f-a025-931fceb17125.png)
正常的噢

**Comment by Zacharry** [comment]
> > 没Bypass之前测试cs的payload是可以上线了，按照pdf流程后，运行main.exe，无法上线，我还重来了一遍，也是不行，不知道是哪一步出现了问题
> 
> ![2022-04-04_132239](https://user-images.githubusercontent.com/66585732/161479194-0abe8059-802a-4c0f-a025-931fceb17125.png) 正常的噢

已成功，初步估计原因是环境变量mingw32的排序在最后，我把mingw32环境变量排序置顶后，正常上线，谢谢表哥
![1](https://user-images.githubusercontent.com/45279782/161484969-e179485e-2cea-4ae1-86b7-b5e913bda794.png)
